spring:
  application:
    name: devops-practices
server:
  port: 8090

logging:
  level:
    com.example.devopspractices: DEBUG
    org.zalando.logbook.Logbook: TRACE

logbook:
  filter:
    enabled: true